version: "3"
services:
 phala-node:
   image: phalanetwork/khala-node
   container_name: phala-node
   hostname: phala-node
   ports:
    - "9933:9933"
    - "9934:9934"
    - "9944:9944"
    - "9945:9945"
    - "30333:30333"
    - "30334:30334"
   environment:
    - NODE_NAME=khala_node
    - NODE_ROLE=MINER
   volumes:
    - /var/khala-dev-node:/root/data
